// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
[assembly: AssemblyInformationalVersionAttribute("1.0.1 b6b3aa")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.0.1";
        internal const System.String AssemblyFileVersion = "1.0.1";
        internal const System.String AssemblyInformationalVersion = "1.0.1 b6b3aa";
    }
}
